import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import iconArrowR from "@/images/iconArrowR.svg";
import Navbar from '@/components/Navbar';
import ButtonTextAndImage from '@/components/ButtonTextAndImage';
import Image from "next/image";
import imgBanner from "@/images/imgBanner.svg";
import rapide from "@/images/rapide.png"
import { useRouter } from 'next/navigation';
import useTranslation from 'next-translate/useTranslation';
import Thematic from '@/components/Thematic';
import PreviewRecipe from '@/components/PreviewRecipe';
import IconBreakfast from "@/images/iconBreakfast.svg";
import IconDinner from "@/images/dinner.svg";
import IconHealthy from "@/images/Healthy.svg";
import IconLunch from "@/images/lunch.svg";
import IconMeat from "@/images/meat.svg";
import IconDessert from "@/images/sweet.svg";
import Button from '@/components/Button';
import { styleButton } from '@/utils/stylesFunction';

export default function Home() {
  const router = useRouter();
  const t_home = useTranslation('home').t;
  const t_global = useTranslation('globals').t;


  const getPopularRecipes = () => <PreviewRecipe recipes={{
    name: 'Mdr',
    notes: 4.3,
    nbrAvis: 2,
    img: ''
  }}/>
  
  return (
    <>
      <Head>
        <title>{t_global("nameSite")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <section className={styles.containerCover}>
          <div className={styles.containerImgCover}>
            <ButtonTextAndImage 
                text={t_home("buttonBestRecipes")} 
                img={iconArrowR} 
                imgRight
                style={{position : "absolute", bottom : 0, right : 0, transform : "translate(-10%, -50%)"}}/>
            <Image src={imgBanner} alt={""}/>
          </div>
        </section>
        <section className={styles.containerContent}>
          <h2>Inspiration thématique </h2>
          <div className={styles.containerThematics}>
            {/* <Thematic name={'Rapide'} img={rapide}/> */}
            <Thematic name={t_home("textThematic.Breakfast")} img={IconBreakfast}/>
            <Thematic name={t_home("textThematic.Lunch")} img={IconLunch}/>
            <Thematic name={t_home("textThematic.Dinner")} img={IconDinner}/>
            <Thematic name={t_home("textThematic.Meat")} img={IconMeat}/>
            <Thematic name={t_home("textThematic.Healthy")} img={IconHealthy}/>
            <Thematic name={t_home("textThematic.Dessert")} img={IconDessert}/>
          </div>

          {/* <div className={styles.containerPopularRecipes}>
            <h2>Les recettes du moment !</h2>
            <div className={styles.containerListRecipes}>
              {[...Array(35)].map((_) => getPopularRecipes())}
            </div>
            
          </div> */}
          
          <div className={styles.containerRecipeRandom}>
            <p>{t_home("RecipeRandom.text")}</p>
            <Button style={styleButton(1)} text={t_home("RecipeRandom.textButton")} onPress={function (): void {
              throw new Error('Function not implemented.');
            } }/>
          </div>
        </section>
         
      </main>
    </>
  )
}
