import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import iconArrowR from "@/images/iconArrowR.svg";
import Navbar from '@/components/Navbar';
import ButtonTextAndImage from '@/components/ButtonTextAndImage';
import Image from "next/image";
import imgBanner from "@/images/imgBanner.svg";
import rapide from "@/images/rapide.png"
import { useRouter } from 'next/navigation';
import useTranslation from 'next-translate/useTranslation';
import Thematic from '@/components/Thematic';
import PreviewRecipe from '@/components/PreviewRecipe';

export default function Home() {
  const router = useRouter();
  const t_home = useTranslation('home').t;
  const t_global = useTranslation('globals').t;


  const getPopularRecipes = () => <PreviewRecipe recipes={{
    name: 'Mdr',
    notes: 4.3,
    nbrAvis: 2,
    img: ''
  }}/>
  
  return (
    <>
      <Head>
        <title>{t_global("nameSite")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <section className={styles.containerCover}>
          <div className={styles.containerImgCover}>
            <ButtonTextAndImage 
                text={t_home("buttonBestRecipes")} 
                img={iconArrowR} 
                imgRight
                style={{position : "absolute", bottom : 0, right : 0, transform : "translate(-10%, -50%)"}}/>
            <Image src={imgBanner} alt={""}/>
          </div>
        </section>
        <section className={styles.containerContent}>
          <h2>Inspiration thématique </h2>
          <div className={styles.containerThematics}>
            <Thematic name={'Rapide'} img={rapide}/>
          </div>

          <div className={styles.containerPopularRecipes}>
            <h2>Les recettes du moment !</h2>
            <div className={styles.containerListRecipes}>
              {[...Array(35)].map((_) => getPopularRecipes())}
            </div>
            
          </div>
        </section>
         
      </main>
    </>
  )
}
